extends:
  - stylelint-config-standard
  - stylelint-config-css-modules

rules:
  custom-property-pattern: null
  declaration-empty-line-before: null
  font-family-name-quotes: null
  font-family-no-missing-generic-family-keyword: null
  function-url-quotes: null
  keyframes-name-pattern: null
  length-zero-no-unit: null
  no-descending-specificity: null
  property-no-vendor-prefix:
    - true
    - ignoreProperties:
        - background-clip
  selector-class-pattern: null
  selector-id-pattern: null
  shorthand-property-no-redundant-values: null
  value-keyword-case: null
  media-feature-range-notation:
    # Until Safari 16.3 and Chrome 103 are no longer supported (https://caniuse.com/css-media-range-syntax)
    - 'prefix'
