compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishAccess: public

npmMinimalAgeGate: '3d'

# Packages to except from the npmMinimalAgeGate. Currently this mainly contains
# other packages we've authored that we are likely to often want to immediately
# update to after publishing a new version of it.
npmPreapprovedPackages:
  [
    'contain-by-screen',
    'live-set',
    'matches-selector-ng',
    'order-manager',
    'page-parser-tree',
    'tag-tree',
  ]

yarnPath: .yarn/releases/yarn-4.13.0.cjs
