export default {
	getLogger: 0,
	getRouteViewDriverStream: 0,
	getRowListViewDriverStream: 0,
	openComposeWindow: 0,
	getComposeViewDriverStream: 0,
	getThreadViewDriverStream: 0,
	getMessageViewDriverStream: 0,
	createKeyboardShortcutHandle: 3,
	getUserEmailAddress: 0,
	getThreadRowViewDriverKefirStream: 0,
	addNavItem: 2,
	getSentMailNativeNavItem: 0,
	createLink: 2,
	goto: 2,
	addCustomRouteID: 1,
	addCustomListRouteID: 2,
	showCustomRouteView: 1,
	getCurrentActiveNavItem: 0,

	setNativeRouteIDs: 1,
	setNativeListRouteIDs: 1,
	setRouteTypes: 1,

	registerSearchSuggestionsProvider: 1,
	registerSearchQueryRewriter: 1,
	addToolbarButtonForApp: 1,
	getToolbarViewDriverStream: 0,
	getButterBarDriver: 0,
	createModalViewDriver: 1
};
