// Generated by CoffeeScript 1.7.1
var reload_tabs;

reload_tabs = function() {
  var content_script, manifest, _i, _len, _ref;
  manifest = chrome.runtime.getManifest();
  _ref = manifest.content_scripts;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    content_script = _ref[_i];
    chrome.tabs.query({
      url: content_script.matches
    }, function(tabs) {
      var tab, _j, _len1;
      for (_j = 0, _len1 = tabs.length; _j < _len1; _j++) {
        tab = tabs[_j];
        chrome.tabs.reload(tab.id);
      }
    });
  }
};

chrome.runtime.onInstalled.addListener(function(details) {
  var on_install;
  on_install = function(guid) {
    var version;
    version = chrome.runtime.getManifest().version;
    if (details.reason === "install") {
      Util.log("install", guid, "", version);
      reload_tabs();
    } else if (details.reason === "update") {
      Util.log("upgrade", guid, "", version, {
        previous_version: details.previousVersion
      });
    }
  };
  chrome.storage.local.get("guid", function(items) {
    var guid;
    if (items.guid != null) {
      on_install(items.guid);
    } else {
      guid = Util.generate_guid();
      chrome.storage.local.set({
        "guid": guid
      }, function() {
        on_install(guid);
      });
    }
  });
});
