// Generated by CoffeeScript 1.9.3
var ORIGIN;

ORIGIN = "https://mail.google.com";

document.addEventListener("DOMContentLoaded", function() {
  var chooser;
  chooser = document.createElement("iframe");
  chooser.src = (DROPBOX_BASE + "/chooser?app_key=" + (encodeURIComponent(DROPINS_APP_KEY)) + "&version=3&") + ("origin=" + (encodeURIComponent(ORIGIN)) + "&iframe=true&multiselect=true&folderselect=true");
  document.body.appendChild(chooser);
});
