// Generated by CoffeeScript 1.7.1
var CDN_BASE, DBX_LINK_RE, DROPBOX_BASE, DROPINS_APP_KEY, DROPINS_URL, SDK_APP_ID;

DROPBOX_BASE = "https://www.dropbox.com";

CDN_BASE = "https://cf.dropboxstatic.com";

DROPINS_URL = "" + DROPBOX_BASE + "/static/api/2/dropins.js";

DROPINS_APP_KEY = "82bgsya5b7h847j";

SDK_APP_ID = "dropbox";

DBX_LINK_RE = /^https:\/\/(www|carousel)\.(dropbox|carousel)\.com\//;
