// Generated by CoffeeScript 1.9.1
var CDN_BASE, DBX_LINK_RE, DROPBOX_BASE, DROPINS_APP_KEY, DROPINS_URL, EMAIL_HASH_BLACKLIST, SDK_APP_ID;

DROPBOX_BASE = "https://www.dropbox.com";

CDN_BASE = "https://cf.dropboxstatic.com";

DROPINS_URL = DROPBOX_BASE + "/static/api/2/dropins.js";

DROPINS_APP_KEY = "82bgsya5b7h847j";

SDK_APP_ID = "dropbox";

DBX_LINK_RE = /^https:\/\/(www|carousel)\.(dropbox|carousel)\.com\//;

EMAIL_HASH_BLACKLIST = ["8997f8f2a2469665e94ade58475c2f605a7a42de"];
