// Generated by CoffeeScript 1.7.1
var Util;

Util = {
  get_filename: function(path) {
    return path.split('/').pop();
  },
  get_ext: function(path) {
    var ext_split, filename;
    filename = this.get_filename(path);
    ext_split = filename.split('.');
    if (ext_split.length === 1 || (ext_split.length === 2 && !ext_split[0])) {
      return "";
    } else {
      return ext_split.pop();
    }
  },
  generate_guid: function() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r, v;
      r = Math.random() * 16 | 0;
      v = c === 'x' ? r : r & 0x3 | 0x8;
      return v.toString(16);
    });
  },
  log: function(event_name, guid, key, version, extra) {
    var data, xhr;
    if (extra == null) {
      extra = {};
    }
    data = new FormData();
    data.append("event_name", event_name || "");
    data.append("guid", guid || "");
    data.append("key", key || "");
    data.append("version", version || "");
    data.append("extra", JSON.stringify(extra));
    xhr = new XMLHttpRequest();
    xhr.open("POST", "" + DROPBOX_BASE + "/gmail_extension_log", true);
    xhr.send(data);
  }
};
